using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace QAFood.Migrations.ApplicationDb
{
    public partial class Update1 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
               name: "FK_TestResultItems_LOV_CategoryId",
               table: "TestResultItems");
            
            // Need to move data from LOV into TestItemCategories before it is deleted.
            // This is not autogenerated code. The DropForiegnKey and DropTable statements needed to be moved.
            // It is easier to rename the table instead of dropping it and creating a new one.
            migrationBuilder.RenameTable("LOV", newName: "TestItemCategories");
            migrationBuilder.DropColumn("Context", "TestItemCategories");
            migrationBuilder.DropPrimaryKey("PK_LOV", "TestItemCategories");
            migrationBuilder.AddPrimaryKey("PK_TestItemCategories", "TestItemCategories", "Id");
           
            migrationBuilder.AddForeignKey(
                name: "FK_TestResultItems_TestItemCategories_CategoryId",
                table: "TestResultItems",
                column: "CategoryId",
                principalTable: "TestItemCategories",
                principalColumn: "Id",
                onDelete: ReferentialAction.NoAction);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Do not allow going back from this version. You will lose data and foriegn key violation will happen.
            throw new System.Exception("You cannot undo Update1. Data will be lost if you return to a previous version");

            migrationBuilder.DropForeignKey(
                name: "FK_TestResultItems_TestItemCategories_CategoryId",
                table: "TestResultItems");

            migrationBuilder.DropTable(
                name: "TestItemCategories");

            migrationBuilder.CreateTable(
                name: "LOV",
                columns: table => new
                {
                    Id = table.Column<long>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Context = table.Column<string>(maxLength: 256, nullable: false),
                    Value = table.Column<string>(maxLength: 256, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_LOV", x => x.Id);
                });

            migrationBuilder.AddForeignKey(
                name: "FK_TestResultItems_LOV_CategoryId",
                table: "TestResultItems",
                column: "CategoryId",
                principalTable: "LOV",
                principalColumn: "Id",
                onDelete: ReferentialAction.NoAction);
        }
    }
}
